/*********************************************************************
 * SYNOPSYS CONFIDENTIAL                                             *
 *                                                                   *
 * This is an unpublished, proprietary work of Synopsys, Inc., and   *
 * is fully protected under copyright and trade secret laws. You may *
 * not view, use, disclose, copy, or distribute this file or any     *
 * information contained herein except pursuant to a valid written   *
 * license from Synopsys.                                            *
 *********************************************************************/

#include <systemc.h>
#include "tli_packunpack_my_payload.h"

// Wrapper functions required by the TLI for user defined payloads
// (should be generated by syscan -tli)

template <typename T>
void tli_conv2_unpack_tlmgp(tli_pack_data& bytes, T &tr)
{
    tli_conv2_unpack_my_payload(bytes, tr);
}

template <typename T>
void tli_conv2_pack_tlmgp(tli_pack_data& bytes, T &tr)
{
    tli_conv2_pack_my_payload(bytes, tr);
}

template void tli_conv2_pack_tlmgp<my_payload>(tli_pack_data& , my_payload&);
template void tli_conv2_unpack_tlmgp<my_payload>(tli_pack_data& , my_payload&);
