$DUT_SRC/rtl/vhdl/fpupack.vhd
$DUT_SRC//rtl/vhdl/comppack.vhd
$DUT_SRC/rtl/vhdl/addsub_28.vhd
$DUT_SRC/rtl/vhdl/fpu.vhd
$DUT_SRC/rtl/vhdl/mul_24.vhd
$DUT_SRC/rtl/vhdl/post_norm_addsub.vhd
$DUT_SRC/rtl/vhdl/post_norm_div.vhd
$DUT_SRC/rtl/vhdl/post_norm_mul.vhd
$DUT_SRC/rtl/vhdl/post_norm_sqrt.vhd
$DUT_SRC/rtl/vhdl/pre_norm_addsub.vhd
$DUT_SRC/rtl/vhdl/pre_norm_div.vhd
$DUT_SRC/rtl/vhdl/pre_norm_mul.vhd
$DUT_SRC/rtl/vhdl/pre_norm_sqrt.vhd
$DUT_SRC/rtl/vhdl/serial_div.vhd
$DUT_SRC/rtl/vhdl/serial_mul.vhd
$DUT_SRC/rtl/vhdl/sqrt.vhd
